__version__ = "5.1.0"
__author__ = "Tomasz Łuczak"
__email__ = "tlu@team-tl.pl"
__appname__ = "FotoKilof"
__description__ = "Nice gui for ImageMagick"
__keywords__ = "GUI ImageMagick FotoKilof"
__url__ = "https://github.com/TeaM-TL/FotoKilof"
__copyright__ = "2019-2024"